project:
   type: book
   output-dir: docs

book:
  title: "R과 통계분석, 4판"
  subtitle: "Tidyverse 활용"
  author: "박동련"
  cover-image: "Figure/cover.png"
  date: last-modified
  chapters:
    - index.qmd
    - 01-intro-4e.qmd
    - 02-dplyr-4e.qmd
    - 03-ggplot2-4e.qmd
    
format:
  html:
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 3
#    theme: cosmo
    code-fold: true

knitr:
  opts_chunk: 
    collapse: true
    comment: "" 
    prompt: true
    fig.width: 4
    fig.height: 2.5
   
execute: 
  message: false
  warning: false
  

crossref: 
#  chapters: true
  fig-title: "그림 "
  fig-prefix: ""
  tbl-title: "표 "
  tbl-prefix: ""
  sec-prefix: ""

# quarto render